config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  patch 'users/update_account' => 'users#update_account', :as => :update_account
  patch 'users/update_password' => 'users#update_password', :as => :update_password
  patch 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get 'topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  patch 'upyun_images' => 'upyun_images#create'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        patch :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    patch :toggle_comments_closed
    patch :toggle_sticky
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images, :qiniu_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      patch :move_to, :on => :member
    end

    resources :users do
      member do
        patch :toggle_admin
        patch :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root 'welcome_admin#index'
  end

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id              :integer          not null, primary key
#  node_id         :integer
#  user_id         :integer
#  title           :string(255)
#  content         :text(65535)
#  hit             :integer
#  involved_at     :datetime
#  comments_count  :integer          default(0)
#  comments_closed :boolean          default(FALSE)
#  sticky          :boolean          default(FALSE)
#  last_replied_by :string(255)      default("")
#  last_replied_at :datetime
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Topic < ApplicationRecord
  include Notifiable

  DEFAULT_HIT = 0
  # default_value_for :hit, DEFAULT_HIT
  # default_value_for :content, ''
  # default_value_for :involved_at do
  #   Time.zone.now
  # end

  belongs_to :node, :touch => true, :counter_cache => true
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :bookmarks, :as => :bookmarkable, :dependent => :destroy
  has_many :notifications, :as => :notifiable, :dependent => :destroy

  validates :node_id, :user_id, :title, :presence => true

  before_create do
    self[:hit] = 0
    self[:involved_at] = Time.zone.now
    self[:content] = '' if content.nil?
  end

  after_create :send_notifications

  def last_comment
    self.comments.order('created_at ASC').last
  end

  def locked?
    Time.now - self.created_at > Siteconf.topic_editable_period
  end

  def allow_modification_by?(user)
    (!locked? && self.user == user) || user.can_manage_site?
  end

  def notifiable_title
    title
  end

  def notifiable_path
    "/t/#{id}"
  end

  def self.sticky_topics
    with_sticky(true).order('updated_at DESC').all
  end

  def self.home_topics(num)
    excluded_nodes = Node.where(:quiet => true).pluck(:id)
    if excluded_nodes.any?
      where("node_id NOT in (?)", excluded_nodes).with_sticky(false).latest_involved_topics(num)
    else
      with_sticky(false).latest_involved_topics(num)
    end
  end

  def self.with_sticky(sticky)
    where(:sticky => sticky)
  end

  def self.latest_involved_topics(num)
    order('involved_at DESC').limit(num).all
  end

  def self.recent_topics(num)
    ts = select('updated_at').order('updated_at DESC').first.try(:updated_at)
    return Rabel::Model::EMPTY_DATASET unless ts.present?
    Rails.cache.fetch("topics/recent/#{self.count}/#{num}-#{ts}") do
      order('involved_at DESC').limit(num).all
    end
  end

  def mention_check_text
    self.title + self.content rescue ''
  end

  def mentioned_users
    mentioned_names = self.mention_check_text.scan(Notifiable::MENTION_REGEXP).collect {|matched| matched.first}.uniq
    mentioned_names.delete(self.user.nickname)
    mentioned_names.map { |name| User.find_by_nickname(name) }.compact
  end

  def prev_topic(node)
    node.topics.where(['id < ?', self.id]).order('created_at DESC').first
  end

  def next_topic(node)
    node.topics.where(['id > ?', self.id]).order('created_at ASC').first
  end

  private

    def send_notifications
      mentioned_users.each do |user|
        Notification.notify(
          user,
          self,
          self.user,
          Notification::ACTION_TOPIC,
          self.content
        )
      end
    end


end

app/controllers/admin/topics_controller.rb
# encoding: utf-8
class Admin::TopicsController < Admin::BaseController
  def index
    @topics = Topic.order('created_at DESC').page(params[:page])
    @title = '讨论话题'
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      redirect_to admin_topics_path
    else
      redirect_to admin_root_path
    end
  end
end

app/controllers/topics_controller.rb
# encoding: utf-8
class TopicsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :find_node, :except => [:show, :index, :preview, :toggle_comments_closed, :toggle_sticky, :new_from_home, :create_from_home]
  before_action :find_topic_and_auth, :only => [:edit_title,:update_title,
    :edit, :update, :move, :destroy]

  before_action :only => [:toggle_comments_closed, :toggle_sticky] do |c|
    auth_admin
  end

  skip_before_action :verify_authenticity_token, only: [:preview]

  def index
    respond_to do |format|
      format.html {
        per_page = Siteconf::HOMEPAGE_TOPICS
        @title = '全站最新更改记录'
        if params[:page].present?
          current_page = params[:page].to_i
          @title += " (第 #{current_page} 页)"
        else
          current_page = 1
        end

        @topics = Topic.page(current_page).per(per_page).order('updated_at DESC')

        @canonical_path = topics_path
        @canonical_path += "?page=#{current_page}" if current_page > 1

        @seo_description = @title
      }
      format.atom {
        @feed_items = Topic.recent_topics(Siteconf::HOMEPAGE_TOPICS)
        @last_update = @feed_items.first.updated_at unless @feed_items.empty?
        render :layout => false
      }
    end
  end

  def show
    raise ActiveRecord::RecordNotFound.new if params[:id].to_i.to_s != params[:id]

    @topic = Topic.find(params[:id])
    store_location

    Topic.increment_counter(:hit, @topic.id)

    @title = @topic.title
    @node = @topic.node

    @total_comments = @topic.comments.count
    @total_pages = (@total_comments * 1.0 / Siteconf.pagination_comments.to_i).ceil
    @current_page = params[:p].nil? ? @total_pages : params[:p].to_i
    @per_page = Siteconf.pagination_comments.to_i
    @comments = @topic.comments.page(@current_page).per(@per_page).order('created_at ASC')

    @new_comment = @topic.comments.new
    @total_bookmarks = @topic.bookmarks.count

    @canonical_path = "/t/#{params[:id]}"
    @canonical_path += "?p=#{@current_page}" if @total_pages > 1
    @seo_description = "#{@node.name} - #{@topic.user.nickname} - #{@topic.title}"

    @prev_topic = @topic.prev_topic(@node)
    @next_topic = @topic.next_topic(@node)

    respond_to do |format|
      format.html
    end
  end

  def new
    @topic = @node.topics.new

    respond_to do |format|
      format.html
    end
  end

  def new_from_home
    @topic = Topic.new
    @topic.node = Node.find(params[:node_id]) if params[:node_id]
  end

  def create
    @topic = @node.topics.new(topic_params)
    @topic.user = current_user
    if @topic.save
      redirect_to t_path(@topic.id)
    else
      render :new
    end
  end

  def create_from_home
    @node = Node.where(id: params[:topic][:node_id]).first
    redirect_to root_path and return if @node.nil?

    @topic = Topic.new(topic_params)
    @topic.node = @node
    @topic.user = current_user

    if @topic.save
      redirect_to t_path(@topic.id)
    else
      render :new_from_home
    end
  end

  def edit_title
    respond_to do |f|
      f.js
    end
  end

  def update_title
    respond_to do |f|
      f.js {
        unless @topic.update_attributes(topic_params)
          render :text => :error, :status => :unprocessable_entity
        end
      }
    end
  end

  def edit
  end

  def update
    if params[:new_node_id].present?
      # move to new node
      @new_node = Node.find(params[:new_node_id])
      respond_to do |format|
        format.js {
          if @new_node.present?
            @topic.node = @new_node
            if @topic.save
              render :js => "window.location.reload()"
            else
              render :js => "$.facebox('移动帖子失败')"
            end
          else
            render :js => "$.facebox('节点不存在')"
          end
        }
      end
    else
      if @topic.update_attributes(topic_params)
        redirect_to t_path(@topic.id)
      else
        flash[:error] = '之前的更新有误，请编辑后再提交'
        render :edit
      end
    end
  end

  def move
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @topic.destroy
      redirect_to root_path, :notice => '帖子删除成功'
    else
      raise RuntimeError.new('删除帖子出错')
    end
  end

  def preview
    @type = ['topic', 'comment', 'page'].delete params[:type]
    respond_to do |f|
      if @type.present?
        f.text { @content = params[:content] }
      else
        render :text => :error, :status => :unprocessable_entity
      end
    end
  end

  def toggle_comments_closed
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:comments_closed)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  def toggle_sticky
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:sticky)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  private
    def find_node
      @node = Node.find(params[:node_id])
    end

    def find_topic_and_auth
      @topic = @node.topics.find(params[:id])
      authorize! :update, @topic, :message => '你没有权限管理此主题'
    end

    def topic_params
      if current_user.can_manage_site?
        params.require(:topic).permit(:title, :content, :comments_closed, :sticky)
      else
        params.require(:topic).permit(:title, :content)
      end
    end
end

app/views/topics/_back_to_node.html.haml
%span.fade
  %span.chevron ‹&nbsp;
  返回
  = link_to node.name, go_path(node.key)

app/views/topics/_form.html.haml
.alert.alert-info 如果标题已经包含你想说的话，内容可以留空
= simple_form_for [node, topic] do |f|
  %a{:name => 'new_topic'}/
  = f.input :title, :label => '标题', :input_html => {:maxlength => 150, :class => :span6}
  = render 'shared/fileupload_widget', :textarea_selector => "textarea#topic_content"
  = render 'shared/preview_widget', :ref => :topic_content, :type => :topic
  = f.input :content, :input_html => {:rows => 10}, :label => false, :placeholder => '话题内容'
  - if current_user.can_manage_site?
    .checkbox
      = f.input :sticky, :inline_label => '保持置顶', :label => false
    .checkbox
      = f.input :comments_closed, :inline_label => '禁止回复', :label => false
  = f.submit (topic.new_record? ? '创建新话题' : '提交修改'), :class => 'btn btn-primary', :data => {:disable_with => t('tips.submitting')}

app/views/topics/_move_form.js.haml
= form_for [@node, @topic], :remote => :true do |f|
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h3.modal-title 移动到新节点
      .modal-body
        .form-group
          = label_tag '移动到新节点'
          = select_tag "new_node_id", option_groups_from_collection_for_select(Plane.default_order.all, :nodes, :name, :id, :name, f.object.node.id), class: 'form-control'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 取消
        -# = f.submit '确定', :class => 'btn btn-primary', :data => {:disable_with => t('tips.submitting')}
        = f.submit '开始移动', :class => 'btn btn-primary'

app/views/topics/_profile_topic.html.haml
- topic_node = topic.node
- comments_count = topic.comments.count
- last_replied_by = topic.last_replied_by
.cell.topic{:class => topic_user.can_manage_site? ? 'admin' : ''}
  %table{:cellpadding => 0, :cellspacing => 0, :border => 0, :width => '100%'}
    %tr
      %td{:valign => :middle, :width => :auto}
        %span.bigger
          = link_to topic.title, t_path(topic.id), :class => 'rabel topic'
        .topic-meta
          = link_to topic_node.name, go_path(topic_node.key), :class => :node
          - if comments_count > 0
            &nbsp;&nbsp;•&nbsp;&nbsp;
            = time_ago_in_words(topic.last_replied_at)
            &nbsp;&nbsp;•&nbsp;&nbsp;
            最后回复来自
            = nickname_profile_link(last_replied_by)
          - else
            &nbsp;&nbsp;•&nbsp;&nbsp;
            = time_ago_in_words(topic.created_at)
      %td{:valign => :middle, :width => 40, :align => :right}
        .badge.badge-info= comments_count

app/views/topics/_table_view.html.haml
%table{:cellpadding => 5, :cellspacing => 0, :border => 0, :width => '100%', :class => :topics}
  %tr
    %th{:align => :right, :width => 50} 回复
    %th{:align => :left, :width => :auto} 标题
    %th{:align => :left, :width => 200, :colspan => 2} 最后回复时间
  - i = 1
  - topics.each do |topic|
    - class_name = (i % 2 == 0) ? 'even' : 'odd'
    - i += 1
    %tr
      %td{:align => :right, :width => 50, :class => "#{class_name} lend"}
        - comments_count = topic.comments.count
        - if comments_count > 0
          %strong
            %span.green= comments_count
        - else
          %span.snow 0
      %td{:align => :left, :width => :auto, :class => class_name}
        = link_to topic.title, t_path(topic.id)
      - last_comment = topic.last_comment
      - last_comment = topic if last_comment.nil?
      %td{:align => :left, :width => 80, :class => class_name}
        = user_profile_link(last_comment.user, :class => :dark)
      %td{:align => :left, :width => 120, :class => "#{class_name} rend"}
        %small.fade= last_comment.created_at.strftime("%Y-%m-%d %H:%M:%S")

app/views/topics/_title_form.html.haml
= form_for [@node, @topic], :url => update_title_node_topic_path(@node, @topic), :remote => true do |f|
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h3.modal-title 修改标题
      .modal-body
        %a{:name => 'new_topic'}
        .form-group
          = f.label :title, '标题'
          = f.text_area :title, :id => 'modal-edit-title', :class => 'form-control', :rows => 2, :autofocus => true
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 取消
        = f.submit '确定', :class => 'btn btn-primary', :data => {:disable_with => t('tips.submitting')}

app/views/topics/_topic.html.haml
- topic_user = topic.user
- topic_node = topic.node
- comments_count = topic.comments.count
- last_replied_by = topic.last_replied_by
.cell.topic{:class => topic_user.can_manage_site? ? 'admin' : ''}
  .avatar.pull-left
    = user_profile_avatar_link(topic_user, :medium)
  .item_title
    - if comments_count > 0
      .pull-right
        .badge.badge-info= comments_count
    %h2.topic_title
      = link_to topic.title, t_path(topic.id), :class => 'rabel topic'
    .topic-meta
      = link_to topic_node.name, go_path(topic_node.key), :class => :node
      %span.muted •
      = user_profile_link(topic_user, :class => :dark)
      %span.muted •
      - if comments_count > 0
        = time_ago_in_words(topic.last_replied_at)
        %span.muted •
        最后回复来自
        = nickname_profile_link(last_replied_by)
      - else
        = time_ago_in_words(topic.created_at)

app/views/topics/edit_title.js.haml
-# $.facebox("#{escape_javascript(render('title_form'))}")
$('#edit-modal').html("#{escape_javascript(render('title_form'))}");
$('#edit-modal').modal('show');

app/views/topics/index.html.haml
.box
  .cell= build_navigation([@title])
  = render @topics
  .inner{:align => :center}
    = paginate @topics

app/views/topics/new.html.haml
.box
  .cell
    = build_navigation [link_to(@node.name, go_path(@node.key))]
  .inner
    %h2 创建新话题
    = render 'form', :node => @node, :topic => @topic, :comments_closed => false

app/views/topics/new_from_home.html.slim
.box
  .cell
    h2 创建新话题
  .inner
    = simple_form_for @topic, :url => create_from_home_topics_path do |f|
      = f.input :title, :label => '标题', :input_html => {:maxlength => 150, :class => :span6}
      = render 'shared/fileupload_widget', :textarea_selector => "textarea#topic_content"
      = render 'shared/preview_widget', :ref => :topic_content, :type => :topic
      = f.input :content, :input_html => {:rows => 10}, :label => false, :placeholder => '话题内容'
      = f.association :node, :label => false, :collection => Plane.all, :as => :grouped_select, :group_method => :nodes, :prompt => '选择一个节点'
      - if current_user.can_manage_site?
        .checkbox
          = f.input :sticky, :inline_label => '保持置顶', :label => false
        .checkbox
          = f.input :comments_closed, :inline_label => '禁止回复', :label => false
      = f.submit '创建新话题', :class => 'btn btn-primary btn-inverse', :data => {:disable_with => t('tips.submitting')}

app/views/topics/preview.text.haml
- format_method = "format_#{@type}"
= send(format_method, @content)

app/views/topics/show.html.haml
= render 'nodes/custom_fields', :node => @node
-if Siteconf.allow_share_button_in_topic?
  = render('shared/share_buttons')
= render 'topics/show/bookmarked_users'
= render 'topics/show/manage'

- content_for :template_js do
  :plain
    var creating_comment = false;

    $("textarea#comment_content").keydown(function(e) {
      if (e.ctrlKey && e.keyCode == 13) {
        if (creating_comment) return;
        creating_comment = true
        $("input[type=submit]").click();
      }
    });

- topic_user = @topic.user

.box
  %article
    .header
      .pull-right
        = user_profile_avatar_link(topic_user, :large)
      = build_navigation([link_to(@node.name, go_path(@node.key), :class => :rabel)], 'bigger')
      .sep10
      %h1#topic_title
        = Rabel::Base.make_mention_links(Rabel::Base.h(@topic.title)).html_safe
      %small.topic-meta
        By
        = user_profile_link(topic_user, :class => :dark)
        at
        = time_ago_in_words(@topic.created_at)
        ,
        = @topic.hit
        次浏览
      .clearfix
    .inner
      .content.topic_content= format_topic(@topic.content)
      - if user_signed_in?
        .pull-right
          - if current_user.bookmarked?(@topic)
            = link_to '取消收藏', current_user.bookmark_of(@topic), :method => :delete, :class => 'btn btn-xs btn-info unbookmark'
          - else
            = link_to '加入收藏', topic_bookmarks_path(@topic), :method => :post, :class => 'btn btn-xs btn-info bookmark'
      .clearfix
    .inner
      - if @next_topic.present?
        .pull-right
          = link_to proper_length(@next_topic.title, 15), t_path(@next_topic.id), :class => :rabel, :rel => :prev
          %span.guillemet.right-guillemet »


      - if @prev_topic.present?
        .pull-left
          %span.guillemet.left-guillemet «
          = link_to proper_length(@prev_topic.title, 15), t_path(@prev_topic.id), :class => :rabel, :rel => :next

      .clearfix

= render 'topics/show/comments' if @comments.any?

- if @topic.comments_closed?
  = render 'shared/box_tip', :tip => t('tips.comments_closed')
- elsif @comments.empty?
  = render 'shared/box_tip', :tip => '目前尚无回复'

= render 'topics/show/comment_form' unless @topic.comments_closed?

app/views/topics/update_title.js.haml
$("#topic_title").html("#{escape_javascript(@topic.title)}");
$('#edit-modal').modal('hide');